### ISSUE TITLE
Results empty from checking expectations

### ISSUE THREAD

**Issue by mpomarlan** [mpomarlan/schemasim#27]
Returned results appear empty in the demo setup.

**Comment by mpomarlan** [comment]
With a bugfix in #26 this appears solved.

**Comment by shoeffner** [comment]
The results are still empty for me using the [master branch](https://github.com/mpomarlan/schemasim/commit/ecfa8cdacaaf0907108bc1468fa6b4303dd4cf16).

My setup:

```
Object(
    name=cup_0,
    angular_damping=0.5,
    friction=0.75,
    has_collision=1,
    is_kinematic=0,
    linear_damping=0.4,
    mass=0.4,
    mesh=cup/cup.dae,
    physics_type=rigid_body,
    restitution=0.1,
    rw=1.0, rx=0.0, ry=0.0, rz=0.0,
    tx=-0.01419899462288865, ty=-0.04881443884291802, tz=0.22000300742685797,
    type=Cup,
    vx=0.0, vy=0.0, vz=0.0,
    wx=0.0, wy=0.0, wz=0.0,
)
 
Object(
    name=table_0,
    angular_damping=0.5,
    friction=0.7,
    has_collision=1,
    is_kinematic=0,
    linear_damping=0.4,
    mass=1.0,
    mesh=cube/cube.dae,
    physics_type=rigid_body,
    restitution=0.3,
    rw=1.0, rx=0.0, ry=0.0, rz=0.0, 
    tx=0.0, ty=0.0, tz=0.09999999403953552,
    type=Cube,
    vx=0.0, vy=0.0, vz=0.0,
    wx=0.0, wy=0.0, wz=0.0,
)

AxisAlignment(
    a=WorldVerticalDirection(),
    b=UprightDirection(obj=table_0),
)
 
Location(
    locatum=cup_0,
    relatum=table_0,
    spatial_modality=on,
)
```

and the log file is attached.
[animation.log](https://github.com/mpomarlan/schemasim/files/4818893/animation.log)

**Comment by mpomarlan** [comment]
If those are all defined schemas, then there are still no expectations inferrable from them and so not surprising that the results are empty. There are no expectations to check.

Only functional relations define expectations. Support is a functional relation, for example. Location is not.

**Comment by shoeffner** [comment]
Why exactly is location no functional relation, when it's about being "on" something?

**Comment by mpomarlan** [comment]
The simple answer is, because it is not a functional relation :P

The complicated reason is that I needed, for implementation purposes, to clearly distinguish several layers of meaning in sentences such as "cup on the table" and "cup on the hook". When we say something like this, we really mean the functional relation Support, which carries the expectation that whatever object is being supported won't fall (relative to its supporter).

To instantiate a scene where a Support relation exists, there needs to be a less abstract level describing the placements of objects. This is where Location comes in. This level however doesn't describe how objects are supposed to behave, merely how they are initially placed.

There is a gap you're pointing out here: if schemas such as Location/AxisAlignment etc. have procedures to instantiate them, shouldn't they also have procedures to recognize them? The answer is probably yes and I'll open a new issue for this. However in the meantime, if you need to check behavioral expectations, you can already use either the functional relation schemas or explicitly define some expectation schemas in the scene.

**Comment by shoeffner** [comment]
Alright, I now essentially additionally added Support and do get some results. Thank you very much.
I still wonder why "location on" can not be checked as a constraint or expectation, as "being-on-top-of-something" seems to me like a functional relation.

Either way, I guess this is solved (even though my results are unfortunately not what I expected) :) Thank you!

**Comment by mpomarlan** [comment]
This is because development inertia. Schemasim was made to test whether a qualitative scene specification behaves as expected, so I focused on expectations as descriptions of behavior -- and only very high level schemas, the functional relations, put constraints on those -- and assumed that geometric constraints would be enforced by generation.

For the near future, this will morph somewhat and I'll add geometric constraint checking too. See #30 .
