### ISSUE TITLE
Convert the number of frames to a parameter

### ISSUE THREAD

**Issue by shoeffner** [mpomarlan/schemasim#7]
I would love to have the ability to specify the number of frames when running the simulation:
```python
    results = sg.interpretScene([aa, pot, cont, popcorn], bsim, simulate_counterfactuals=False, render=True, nframes=20)
```
I started working on a crude solution but didn't spot all occurences yet, so here is the diff for reference: https://github.com/shoeffner/schemasim/commit/0992ddf7d22629f2436df4325cbe792c44ef5f0c – as discussed in the meeting today, there are probably at least two more places in the script generation where the frame number needs to be adjusted.

**Comment by mpomarlan** [comment]
Done.
