### ISSUE TITLE
Change video format

### ISSUE THREAD

**Issue by shoeffner** [mpomarlan/schemasim#8]
Currently, the blender render output is a `.dvd` file. To display it in [streamlit](https://streamlit.io), I need to convert it to an mp4: `subprocess.run(f'ffmpeg -i {dvd.name} -f mp4 scene.mp4'.split(), cwd=str(path))`.
Can we have mp4 output as a default?

**Comment by mpomarlan** [comment]
Done-- at least, the extension is mp4 after I also changed one of the settings in the scenescript to use "MPEG4" as a format.

**Comment by shoeffner** [comment]
Works beautifully, thanks!
