### ISSUE TITLE
Flexible handling of file paths

### ISSUE THREAD

**Issue by shoeffner** [mpomarlan/schemasim#9]
Currently, there is no way to find the paths the logs, blend files and videos are stored to, as their names are generated as a local variable and time dependent: 

https://github.com/mpomarlan/schemasim/blob/ae9ecda59f7d0b11b0bb3ac9fe45935277ce1453/schemasim/scene_generator.py#L249-L259

Can the path be either returned as metadata inside the result json, or be configurable?
At the moment I hard code the ~/.schemasim_scenes directory, sort the containing files and pick the last – however, if I want to move on to cache simulations for certain sentences, it would be best to be able to keep track of the files etc. – and I think the best point would be to either have a way to specify where the files are stored or to at least returned the location.

**Comment by mpomarlan** [comment]
Done.

As suggested, a new optional parameter has been added to interpretScene: sceneFolder, default value None. Put a string representing a folder path in this parameter if you do not want the results to be stored in the default place (workFolder + str(datetime.now()). If you supply a folder, it doesn't have to exist, but user privileges should be enough to mkdir it.

Also, the scene folder is returned in the dictionary produced by interpretScene, under the "scene_folder" key.
